### ISSUE TITLE
Getting Internal server error 500

### ISSUE THREAD

**Issue by tanuchoudhary21** [tanuchoudhary21/Ruby-granite#1]
I am following BB ruby on rails guide to create granite project. I am facing internal server error when i try to create a new task. I have completed till adding Toaster component in the project. Please help me with the code.

<img width="1438" alt="Screenshot 2021-06-28 at 12 40 49 PM" src="https://user-images.githubusercontent.com/69293348/123600912-bdc9da00-d814-11eb-825d-ee88c72834c8.png">

<img width="556" alt="Screenshot 2021-06-28 at 12 42 40 PM" src="https://user-images.githubusercontent.com/69293348/123600959-c9b59c00-d814-11eb-9352-ed8449deacfa.png">

<img width="557" alt="Screenshot 2021-06-28 at 12 43 40 PM" src="https://user-images.githubusercontent.com/69293348/123601014-d3d79a80-d814-11eb-93ef-779ddf4739c6.png">
@yedhink

**Comment by yedhink** [comment]
@tanuchoudhary21 _a

Please thoroughly go through https://www.bigbinary.com/learn-rubyonrails-book/setting-up-react-environment#jslogger once again.

The logger issue occurs because you haven't properly setup `js-logger`.

**Comment by tanuchoudhary21** [comment]
@yedhink 
I did the logger setup again. I followed all the steps. And i Am still getting error with status 500
<img width="553" alt="Screenshot 2021-06-28 at 2 17 45 PM" src="https://user-images.githubusercontent.com/69293348/123607853-dee1f900-d81b-11eb-8d8e-55d2dc36856d.png">
<img width="817" alt="Screenshot 2021-06-28 at 2 22 12 PM" src="https://user-images.githubusercontent.com/69293348/123608368-51eb6f80-d81c-11eb-9595-f455a58a088f.png">
It shows Error in sources in logger.js file

**Comment by tanuchoudhary21** [comment]
@yedhink 
On the terminal screen It shows the following message , and on the console the above error.

app/controllers/tasks_controller.rb:9:in `create'
Started POST "/tasks/" for ::1 at 2021-06-28 14:40:48 +0530
Processing by TasksController#create as */*
  Parameters: {"task"=>{"title"=>"task1"}}
  TRANSACTION (0.3ms)  begin transaction
  ↳ app/controllers/tasks_controller.rb:9:in `create'
  Task Exists? (1.5ms)  SELECT 1 AS one FROM "tasks" WHERE "tasks"."slug" IS NULL LIMIT ?  [["LIMIT", 1]]
  ↳ app/controllers/tasks_controller.rb:9:in `create'
  Task Create (1.6ms)  INSERT INTO "tasks" ("title", "created_at", "updated_at") VALUES (?, ?, ?)  [["title", "task1"], ["created_at", "2021-06-28 09:10:48.034774"], ["updated_at", "2021-06-28 09:10:48.034774"]]
  ↳ app/controllers/tasks_controller.rb:9:in `create'
  TRANSACTION (0.1ms)  rollback transaction
  ↳ app/controllers/tasks_controller.rb:9:in `create'
Completed 500 Internal Server Error in 18ms (ActiveRecord: 3.5ms | Allocations: 3949)


  
ActiveRecord::NotNullViolation (SQLite3::ConstraintException: NOT NULL constraint failed: tasks.slug):
  
app/controllers/tasks_controller.rb:9:in `create'

**Comment by yedhink** [comment]
@tanuchoudhary21 

I think you've misunderstood the use case of `logger`.

- `logger` is an alternative to `console.log` messages. It's safe to be used since babel will take care of removing it for production bundles.
- Here in the above-attached console statement, the logger is giving out an error.
- When logger gives out an error it doesn't mean that the logger is failing unless error message says otherwise.
- So your first step should be reading the error statement

# error statement

The error statement is pretty on point.

- It has mentioned that the issue is with `CreateTask` component
- And the error is from the server
- Thus our first intuition should be to look up the Task's `create` action in server side
- If you go through you will see that in the `task` model you had missed out on adding a `before_create` call back to set the slug
- This becomes an issue since you had already migrated and have added a constraint that `slug` column cannot be null.

# Solution

![image](https://user-images.githubusercontent.com/31244999/123612536-44d07f80-d820-11eb-8ecf-7ba0b93d4944.png)

From looking at your repo code, I think adding the following callback to `task` model should fix your issue:

```ruby
    before_create :set_slug
``` 

# Why such a long comment?

The idea was to show my thought process and how I approached this issue.

Hopefully you've understood the steps that I took and hope your issue gets fixed.

Thanks

**Comment by tanuchoudhary21** [comment]
@yedhink 
Thank you so much for this great explanation. Yes this has resolved my error. Actually I did add this line but as I proceeded with documentation i got bit confused and removed the line.
Thanks for your help.
